### ISSUE TITLE
[Platform Update]: Attempting to add support for Hera (aka Versa 4 and Sense 2)

### ISSUE THREAD

**Issue by Tsaukpaetra** [remigius42/fitbit-otp-auth-app#1]
### What happened?

Having trouble navigating the proper methods to update the SDK version so it might possibly be portable to these "newer" devices.
I attempted to bodge this by setting the sdk-cli tag to #next and the sdk to #7.1.0-pre.1 , however it seems to be not enough as that magically causes the build to lose track of the sdk-cli library (😕).

For whatever reason the cli is itself having issues properly finding my watch, but I'll assume once I make progress getting the libraries straightened out it will resolve itself.

### Version

1.0 (Default)

### Fitbit device model

Versa 4

### Cellphone model

Android 11

### Formalities

- [X] I agree to follow this project's Code of Conduct
- [X] I confirm that I have read the FAQ and that my issue not covered within
- [X] I confirm that I have looked at the already reported issues and I am sure that this issue would not be a duplicate

**Comment by remigius42** [comment]
Hi @Tsaukpaetra,

thank you for your interest in this repo. Regarding the Fitbit SDK supporting Versa 4 or Sense 2, could you please add the source for this to this issue?
[`fitbit-otp-auth-app`does not support it](https://remigius42.github.io/fitbit-otp-auth-app/app/faq#which-fitbit-devices-are-supported) because AFAIK [neither does the SDK](https://dev.fitbit.com/build/guides/multiple-devices/#devices), [nor are there any plans to support these devices](https://community.fitbit.com/t5/Sense-2/No-apps-are-available-for-the-Sense-2/m-p/5291937#M4442) in the future.
I removed the `bug`label, since this is not a bug of this application.

If you could provide further information regarding the support of newer device, I will try to look into it, what it would mean to support these via a multi device build. Otherwise I will close this issue within the next seven days, since `fitbit-otp-auth-app` officially only supports the Fitbit Versa 3 and Fitbit Sense.

Regards
Andreas

**Comment by Tsaukpaetra** [comment]
Yes apologies for the bug tag, Github would not let me create any request without using the template.
I refer to work by [this user](https://github.com/cmengler/fitbit-app-versa4) who (likely as I did) discovered that the #next tagged versions did add Hera as a target (you can see where this happened in [this commit](https://github.com/Fitbit/fitbit-sdk-toolchain/commit/e09519743fa7296d98ad5deb46f5dd1b8ce68d3b)), and is likely the version of the SDK they're using for the Google Maps app they also recently published.

I actually did manage to get this app to build by properly specifying the dependencies (turns out I was reaching too far ahead for the public firmware API), so I'm currently patching up some weird display issues and other things, here's a (not apparently working) listing for my latest attempt [gallery link](https://gallery.fitbit.com/details/96091468-1dbf-4aa4-9b4b-457f6b42d682).

**Comment by remigius42** [comment]
No problem regarding the `bug` label, I merely stated it to inform you. [I locked down the issues myself](https://github.com/remigius42/fitbit-otp-auth-app/blob/main/.github/ISSUE_TEMPLATE/config.yml) in an attempt to reduce support efforts, which by hindsight might not have been the best course of action.

Thank you for the background information, I just saw that [the commit you mentioned](https://github.com/Fitbit/fitbit-sdk-toolchain/commit/e09519743fa7296d98ad5deb46f5dd1b8ce68d3b) is merged by now and [on master](https://github.com/Fitbit/fitbit-sdk-toolchain/commit/d33bb924ae169e59de87fdbb462dba8b1b4976b0).
I am not sure if the gallery version is ever going to work properly, since as I pointed out, at least [until recently there were no plans to support third-party apps for these devices at all](https://community.fitbit.com/t5/Sense-2/No-apps-are-available-for-the-Sense-2/m-p/5291937#M4442). What the other user might have discovered could be changes made to support new "internal" apps.

In any case, while I can't promise it, I might be able to look into this during the upcoming weekend.
However, I would like to clarify some things first:

- Did you use the [cmengler/fitbit-sdk-build-targets](https://github.com/cmengler/fitbit-sdk-build-targets) to build your app?
- Do you have a Versa 4 or Sense 2 yourself and have tested it on that device?
- Do I assume correctly that you weren't able to run the new versions in the Fitbit OS Simulator?
- Do you intend to use the migrated app just for yourself?

**Comment by Tsaukpaetra** [comment]
- Yes, I added it to the devDependencies
- Yes, I have a Versa 4 I just bought to replace my Charge 5 (and was immediately disappointed when the smart of my Smart Watch ended up being not really so)
- Yeah the binaries aren't in the release version and I didn't dig very hard to find where they might be sourced.
- For now yeah, I just wanted something to tinker with to learn a bit on how to program for my shiny new toy, and this app looked genuinely useful.

Of the things I wanted to adjust, I wanted to add individual token colorization (probably via the progress circle) and encryption-at-rest with pin unlock (because yeah, Fitbit, why isn't this just a built-in permission request) similarly to how the Wallet screens do it.

**Comment by remigius42** [comment]
> Yes, I have a Versa 4 I just bought to replace my Charge 5 (and was immediately disappointed when the smart of my Smart Watch ended up being not really so)

I was thinking about getting a Versa 4 to replace my Versa 3 but I also was rather disappointed that at least officially it seems like third-party apps have been dropped.

> Yeah the binaries aren't in the release version and I didn't dig very hard to find where they might be sourced.

But did you try to run it with for example the Versa 3 profile?
I am asking because I just extracted `Contents/Resources/app.asar` (in the MacOS app package) and the Versa 3 configuration in `main.js` and `renderer.js` only contain limited device specifics, e.g. in `main.js`

```javascript
atlas:{displayName:"Versa 3",modelID:"36",modelType:"WATCH",displayDimensions:{width:336,height:336},buttons:new Set([r.Back]),aodSupported:!0,aodMask:n.default}
```

While it might be possible, that the `modelID` is used internally in the simulator, it would surprise me since I would assume it more likely that at least in the simulator all models share the same base.

> For now yeah, I just wanted something to tinker with to learn a bit on how to program for my shiny new toy, and this app looked genuinely useful.

I think it's a great idea to try to port this to the newer models, even without official support or to add new features making the app more useful. Since this app is released under the GPL, you are more than welcome to do so on your own or preferably to integrate your changes into this repository. Although my spare time is very limited, I would be glad to assist you with code reviews, if contributing your changes back into this project is an option for you. The only thing I should get out of the way I think, is that publishing your extensions on your own would likely have to happen under the GPL as well, since it should qualify as derivative work.

Regarding your modification ideas

* Individual colorization would likely be a nice UX improvement. The reason why I did not considers this so far is my impression, that at least the [official Settings API](https://dev.fitbit.com/build/reference/settings-api/) is quite limited. Even getting the display name configuration to work within the list seemed like kind of a hack. Still, dynamically building a [selection picker](https://dev.fitbit.com/build/reference/settings-api/#select) based on the tokens to switch the target of the color select should probably work.
* On-device encryption is admittedly an issue, which is why by default the app does not store the tokens on the device. I am not even sure if the third-party app data is encrypted on the device by default and I couldn't find any official statements regarding this. But if I understand your idea correctly, this would be more like a PIN unlock when starting the app. I actually considered adding something like that, but eventually dropped it because to be honest, I am not sure how much it would improve the security with respect to the added UX friction. Since the PIN entry has to be reasonably quick, I would assume that the limit is at 6 digits. Depending on how dedicated an attacker is, this would likely only delay the information extraction. However, that is not say that it wouldn't help, since it would give a user at least some time to change their second factor credentials, which currently is not the case.

**Comment by Tsaukpaetra** [comment]
I believe the individual sims are specifically compiled/packaged. Not sure how it is on Mac, but on Windows these are located at `%LocalAppdata%\Programs\@fitbitsimulator\resources\static\devicesim\win` where there's a `runjs.exe` executable for each device type (as given in the appDeviceTypes object), the rest of those dimensions and display data seem more to be about how to present the app host window inside the simulator, and possibly for api requests and the like.

I'll likely fiddle around with it for some time before attempting any kind of pull request, but I'll certainly let you know!

I also think the settings API is a bit jank. I think I saw a way someone made to pop a normal webview and return the data from that back to the settings screen, so perhaps that might be a path forward.

With regards to the pin input, I anticipate to emulate how their implementation of the pay cards works; apparently it's good enough for regulators so I suppose it's probably good enough here too. In my opinion it's primarily to prevent drive-by attacks anyways, which is kinda moot if someone is shoulder-surfing for your other credentials anyways. 🤔

**Comment by remigius42** [comment]
You are absolutely right, I missed the binaries in the `static` folder. That's unfortunate, because I wouldn't be able to test against the new build targets (and as mentioned likely never will be, because I still assume the recent changes made in the Fitbit repositories are motivated by vendored apps and not to reanimate the third-party ecosystem).

Regarding using a webview in the settings, that's a creative approach. However, I would be careful when apps have more restrictive security requirements: in case of this app, I deliberately did not request any [permissions available in the Fitbit SDK](https://dev.fitbit.com/build/guides/permissions/), particularly the [Internet permission](https://dev.fitbit.com/build/guides/permissions/#internet), to prevent the TOTP secrets from being leaked (assuming that the permission model itself is robust enough). Safety measures like this could probably be circumvented via a webview.

My primary concern regarding the PIN entry would be the security vs. UX tradeoff, but that could be ameliorated by allowing the users to choose for themselves whether they want to enable it and after giving it some thought, IMO it could be a nice improvement.

Please feel free to let me know, when I should have a look at some code or if I might help with clarifications regarding this codebase. If for this issue there is nothing left to do in your opinion, please feel free to close it. Otherwise I would probably close it myself in about a week or so and would ask you to open a new issue if need be.

**Comment by Tsaukpaetra** [comment]
Yeah, I'm not sure how the web view thing works but in my mind it should have no need to reach out to an actual Internet site. 

I'll close this for now and if I make any real progress you'll most likely see a pr from me. 😇
